name: Check

on:
  pull_request:
    branches: [$default-branch, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: |
          npm install
          npm install -g nyc
      - name: Tests and Coverage
        run: npm run test -- --coverage
      - name: Report to codecov
        if: ${{ matrix.node-version }} >= 14
        run: |
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
